### ISSUE TITLE
Please make the wiki link accessible

### ISSUE THREAD

**Issue by rothgar** [ccnmtl/omeka#4]
I'm not sure if there's more documentation in the wiki link provided in the README but it would be useful if the data (excluding any sensitive data) were added to the repo or the link were made public.

As it is the link requires a login.

http://wiki.ccnmtl.columbia.edu/index.php/Docker_-izing_Omeka

**Comment by thraxil** [comment]
The wiki page just has basic info about which of our internal servers omeka is deployed to, where the various credentials live in our config management, etc. It's not public because there's really nothing useful there for anyone outside our org.
